### ISSUE TITLE
Need a working example

### ISSUE THREAD

**Issue by alsolh** [siglesiasg/node-red-hyperledger-fabric-gateway#5]
Thank you for your great work, i am trying to run an example and i am getting below errors

10/27/2024, 9:18:13 PM[node: 784c6f5af615db7d](http://localhost:1880/#)
msg : error
"Error: 9 FAILED_PRECONDITION: no endorsers found in the gateway's organization; retry specifying endorsing organization(s) to protect transient data"
10/27/2024, 9:18:13 PM[node: f5670cc282cd7e2f](http://localhost:1880/#)
msg : error
"Error: 9 FAILED_PRECONDITION: evaluate call to endorser returned error: error validating proposal: access denied: channel [businesschannel] creator org [Org1MSP]"

can you please guide me what is the best basic example to run the hyperledger and use your nodes, perhaps with a sample flow?

i was trying to run this hyperledger

https://github.com/yeasy/docker-compose-files/tree/master/hyperledger_fabric

<img width="879" alt="2024-10-27_21-29-24" src="https://github.com/user-attachments/assets/d72087e4-1d3b-4bff-8686-a0c779efc5ee">

**Comment by siglesiasg** [comment]
Hi!

Looking at those errors it may be some incorrect configuration in Hyperledger Fabric, have you been able to send some tx using plain js?

Best way to start up an HLF in local is to use Microfab instead of using a "manual" deployment like in _yeasy_ repository. You have a complete example in `docker` folder with a test chaincode. Check and run [docker-compose.yaml](https://github.com/siglesiasg/node-red-hyperledger-fabric-gateway/blob/main/docker/docker-compose.yaml).
After running that docker-compose with blockchain network running, you can run npm with `start:debug` and you will get a local NodeRed with a testing example flow
